#!/usr/bin/env node
// make-page.mjs — inline the SEVEN gated modules into index.html between the markers, so the
// live page runs the exact code the mutation gate proved. CI regenerates and diffs: the demo
// cannot drift from the gated kernels.
//
// GitHub Pages does not reliably serve .mjs with a JavaScript MIME type, so we inline rather
// than import across files. The only cross-module name collisions are the tiny identical
// helpers `isFin`/`allFin` and the bus's sibling imports — both handled here.
import { readFileSync, writeFileSync } from 'node:fs';

const ORDER = [
  'boundary_control.mjs', 'nacelle_steering.mjs', 'power_chain.mjs',
  'transducer.mjs', 'entropy_surface.mjs', 'replication.mjs', 'bus.mjs',
];

function strip(src) {
  return src.replace(/\r\n/g, '\n').split('\n')
    .filter((l) => !/^\s*import\s/.test(l))                 // drop cross-file imports (all inlined)
    .filter((l) => !/^const isFin = /.test(l))              // shared helper, defined once below
    .filter((l) => !/^const allFin = /.test(l))
    .map((l) => l.replace(/^export\s+/, ''))                // drop export keywords (one scope)
    .join('\n').trim();
}

const helpers = 'const isFin = (v) => Number.isFinite(v);\nconst allFin = (arr) => arr.every(isFin);\n';
const body = ORDER.map((f) => '// ===== ' + f + ' =====\n' + strip(readFileSync(new URL('./' + f, import.meta.url), 'utf8'))).join('\n\n');
const injected = helpers + '\n' + body;

const page = readFileSync(new URL('./index.html', import.meta.url), 'utf8').replace(/\r\n/g, '\n');
const BEGIN = '/* ⟦KERNELS-BEGIN⟧ generated by make-page.mjs from the seven gated .mjs modules — do not edit here */';
const END = '/* ⟦KERNELS-END⟧ */';
const a = page.indexOf(BEGIN), b = page.indexOf(END);
if (a === -1 || b === -1 || b < a) { console.error('markers missing or reversed in index.html'); process.exit(1); }
const next = page.slice(0, a + BEGIN.length) + '\n' + injected + '\n' + page.slice(b);
writeFileSync(new URL('./index.html', import.meta.url), next);
console.log('inlined ' + ORDER.length + ' modules: ' + injected.length + ' chars');
